title: Formations & Ateliers
description: Apprendre en pratiquant, Exp√©rimenter ensemble

baseurl: "/formations" # the subpath of your site, e.g. /blog
url: "https://xavcc.github.io/formations/" # the base hostname & protocol for your site

show_downloads: true
comments: true
logo_url:  /formations/assets/images/logo-formations.png
git_branch: master
theme: 
use_github_wiki: false
use_prose_io: true
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
